sudo: required
language: cpp

os:
        - linux
        - osx

compiler:
        - clang
        - gcc

branches:
        only: v2


before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake boost; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake libboost-all-dev; fi

script:
        - mkdir -p build && cd build
        - cmake ..
        - make
        - ctest
